name: Laravel CI Pipeline

on:
  push:
    branches: [main, ci-workflow]
  pull_request:
    branches: [main, ci-workflow]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_chat_app
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    env:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel_chat_app
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: array
      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql, tokenizer, xml, curl
          ini-values: post_max_size=256M, memory_limit=2G
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Copy .env
        run: cp .env.testing .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            php -r "new PDO('mysql:host=127.0.0.1;dbname=laravel_chat_app', 'root', 'root');" && break
            sleep 3
          done

      - name: Run migrations
        run: php artisan migrate --force

      - name: Seed database
        run: php artisan db:seed --class=DatabaseSeeder

      - name: Run tests with coverage
        run: php artisan test --coverage --coverage-html=storage/coverage-report

      - name: Upload PHPUnit JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: junit.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: storage/coverage-report
