name: Laravel CI Pipeline


on:
  push:
    branches: [main, ci-workflow]
  pull_request:
    branches: [main, ci-workflow]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_chat_app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, mysql, curl, xml, gd
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_chat_app
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate --seed --env=testing

      - name: Clear cache
        run: php artisan config:clear

      - name: Cache config
        run: php artisan config:cache

      - name: Set mail driver
        run: php artisan config:set mail.mailer=array

      - name: Storage link
        run: php artisan storage:link

      - name: Run tests with coverage
        run: php artisan test --coverage --coverage-html=storage/coverage-report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: storage/coverage-report
